feat(medcat-demo-web-app): CU-869b855n0 Manual model access (#230)
* CU-869b855n0: Add models for questionnaire

* CU-869b855n0: Add endpoints for questionnaire

* CU-869b855n0: Use questionnaire endpoints

* CU-869b855n0: Add decorator for requiring valid API key

* CU-869b855n0: Add relevant admin bits to API keys and questions

* CU-869b855n0: Add API-key requiring endpoint

* Fix typo

* Fix another few typos

* CU-869b855n0: Add UI for questionnaire

* CU-869b855n0: Change entry point for questionnaire

* CU-869b855n0: Unify registration of models and their admin stuff

* CU-869b855n0: Move migrations to startup instead of build time

* CU-869b855n0: Collect static at Dockerfile time

* CU-869b855n0: Update migrations

* CU-869b855n0: Update / fix startup commnad

* CU-869b855n0: Remove collectstatic from CMD since it's done at build time

* CU-869b855n0: Fix endpoint from questionnaire to submit

* CU-869b855n0: Fix another endpoint typo

* CU-869b855n0: Fix yet another endpoint typo

* CU-869b855n0: Fix callback URL

* CU-869b855n0: Update template for better accuracy

* CU-869b855n0: Fix URL in setup for callback endpoint

* CU-869b855n0: Add medvat version to more contexts

* CU-869b855n0: Add medcat version to more contexts (in questionnaire)

* CU-869b855n0: Make number of questions dynamic

* CU-869b855n0: Add base template to quiz

* CU-869b855n0: Fix URL in template again

* CU-869b855n0: Add base template to cooldown  template

* CU-869b855n0: Add base template to error template

* CU-869b855n0: Some whitespace changes

* CU-869b855n0: Fix quiz template

* CU-869b855n0: Fix URL for retry on cooldown

* CU-869b855n0: Add link to questionnaire (and UMLS license) to API key based view

* CU-869b855n0: Update template to include details on expiry and attempts

* CU-869b855n0: Fix missing medcat version context

* CU-869b855n0: Centralise cooldown time

* CU-869b855n0: Fix cooldown (hopefully)

* CU-869b855n0: Avoid treating a migration with error in its name as an error

* CU-869b855n0: Avoid mention of API key to lower confusion

* CU-869b855n0: Update messaging for no API-key activation

* CU-869b855n0: Remove question and attempt models

* CU-869b855n0: Remove questionnaire endpoints

* CU-869b855n0: Fix issue with show lib version

* CU-869b855n0: Allow (by default) 14 days for API key cooldown

* CU-869b855n0: Add permission to manually add API keys

* CU-869b855n0: Allow changing expiry date of API key

* CU-869b855n0: Update manual API callback URL

* CU-869b855n0: Add API key link

* CU-869b855n0: Update admin view with correct URL

* CU-869b855n0: Some formatting changes to dockerfile

* CU-869b855n0: Fix copy link

* CU-869b855n0: Remove mention of questionnaire

* CU-869b855n0: Add default value for expiry of API keys

* CU-869b855n0: Update expiry default with picklable method

* CU-869b855n0: Add migration for default expiry

* CU-869b855n0: Minor reword

diff --git a/.github/workflows/medcat-demo-app_build.yml b/.github/workflows/medcat-demo-app_build.yml
--- a/.github/workflows/medcat-demo-app_build.yml
+++ b/.github/workflows/medcat-demo-app_build.yml
@@ -49,7 +49,8 @@ jobs:
     - name: Check container logs for errors
       run: |
         docker-compose logs medcatweb
-        docker-compose logs medcatweb | grep -i 'error' && exit 1 || true
+        # NOTE: ignore line "Applying auth.0007_alter_validators_add_error_messages" - not an error
+        docker-compose logs medcatweb | grep -v "Applying auth.0007_alter_validators_add_error_messages" | grep -i 'error' && exit 1 || true
 
     - name: Tear down
       run: docker-compose -f docker-compose-test.yml down
